#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Put store/description.html into the Gumroad listing's Description field.

WARNING Generated by product/field-note/build.py in the Moonlight working
tree. Edit it there, not here: this file is overwritten on every cycle.

Run by .github/workflows/update-store.yml. Needs GUMROAD_TOKEN in the
environment; without it the workflow never reaches this file.

WARNING This writes to a page that takes money. It sends exactly one field
(description) on exactly one product (the one whose permalink is below), and
it stops rather than guesses at every point where it could be wrong.
"""
import html
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

API = 'https://api.gumroad.com/v2'
PERMALINK = 'kdjdr'
REQUIRED_MARK = 'written by Claude (Anthropic)'
MIN_CHARS = 800

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'description.html')
# WARNING B109. urllib sends `Python-urllib/3.x` unless told otherwise, and
# that string is refused outright by at least one of the venues this project
# writes to (`403 Forbidden Bots`, empty body, no stated cause). Say what this
# is and where its source lives.
AGENT = ('Moonlight/1.0 (+https://github.com/Cele71/moonlight; '
         'an autonomous agent updating its own listing)')


LOG = os.path.join(HERE, 'last-run.txt')
LINES = []


def _summary(text):
    path = os.environ.get('GITHUB_STEP_SUMMARY')
    if path:
        with open(path, 'a', encoding='utf-8') as fh:
            fh.write(text + '\n')


def record(outcome):
    """Append what happened where a reader without a GitHub key can see it.

    WARNING B110. B109 taught this repository that a run's stdout and its job
    summary both need a GitHub token to read, and gave the dev.to updater a
    record() for exactly that reason. This file did not get one. The gate step
    in the workflow wrote GATE SHUT / GATE OPEN and stopped there - so the
    first run where the key actually arrived failed, and the only thing
    visible from outside was the word "failure". The gate was instrumented;
    the thing behind the gate was not.

    WARNING Appends. The gate line is written by the workflow before this
    script starts, and it is the line that says the key exists at all.

    WARNING The token is scrubbed once over the whole text, not per call site.
    """
    token = os.environ.get('GUMROAD_TOKEN', '')
    text = '\n'.join(LINES)
    if token:
        text = text.replace(token, '<redacted>')
    stamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    try:
        with open(LOG, 'a', encoding='utf-8') as fh:
            fh.write('%s  run %s  %s\n\n%s\n'
                     % (stamp, os.environ.get('GITHUB_RUN_ID', '-'),
                        outcome, text))
    except OSError as exc:
        print('could not write %s: %s' % (LOG, exc.__class__.__name__))


def fail(msg):
    # A red step nobody opens is the same as a green one, so it goes in the
    # run summary too - and in last-run.txt, which needs no key at all.
    print('STORE UPDATE ABORTED: ' + msg)
    _summary('### Store description NOT updated\n' + msg)
    LINES.append('ABORTED: ' + msg)
    record('FAILED')
    sys.exit(1)


def note(msg):
    print(msg)
    _summary(msg)
    LINES.append(msg)


def call(method, path, token, fields=None):
    """One request.

    The token travels in the Authorization header, never in the query string:
    a query string is written to every proxy log on the way. If the server
    will not take it there, it is retried in the body - which is not logged -
    and never in the URL.
    """
    def once(in_body):
        data = dict(fields or {})
        if in_body:
            data['access_token'] = token
        body = urllib.parse.urlencode(data).encode('utf-8') if data else None
        req = urllib.request.Request(API + path, data=body, method=method)
        # WARNING B109. Not cosmetic. The other updater in this repository was
        # refused outright - `403 Forbidden Bots` - for sending urllib's
        # default agent string, and the failure named no cause. Say what this
        # is before a venue has to guess.
        req.add_header('User-Agent', AGENT)
        if body is not None:
            req.add_header('Content-Type',
                           'application/x-www-form-urlencoded')
        if not in_body:
            req.add_header('Authorization', 'Bearer ' + token)
        with urllib.request.urlopen(req, timeout=60) as resp:
            return resp.read().decode('utf-8', 'replace')

    raw = None
    try:
        raw = once(False)
    except urllib.error.HTTPError as exc:
        if exc.code not in (401, 403):
            detail = exc.read().decode('utf-8', 'replace')[:400]
            fail('%s %s -> HTTP %s %s'
                 % (method, path, exc.code, detail.replace(token, '<redacted>')))
    except Exception as exc:
        fail('%s %s -> %s' % (method, path, exc.__class__.__name__))
    if raw is None:
        try:
            raw = once(True)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode('utf-8', 'replace')[:400]
            fail('%s %s -> HTTP %s %s'
                 % (method, path, exc.code, detail.replace(token, '<redacted>')))
        except Exception as exc:
            fail('%s %s -> %s' % (method, path, exc.__class__.__name__))
    try:
        return json.loads(raw)
    except ValueError:
        fail('%s %s -> the reply was not JSON' % (method, path))


def find_id(token):
    """The id of the one product this script is allowed to touch."""
    payload = call('GET', '/products', token)
    products = payload.get('products')
    if not isinstance(products, list):
        fail('GET /products did not return a product list')
    needle = '/l/' + PERMALINK
    matches = [p for p in products
               if isinstance(p, dict) and needle in json.dumps(p)]
    if len(matches) != 1:
        fail('%d of %d product(s) match %s - this writes only when exactly '
             'one does' % (len(matches), len(products), needle))
    ident = matches[0].get('id')
    if not isinstance(ident, str) or not ident:
        fail('the matching product has no id field to address it by')
    return ident


def live_description(token, ident):
    payload = call('GET', '/products/' + ident, token)
    product = payload.get('product')
    if not isinstance(product, dict):
        fail('GET /products/<id> did not return a product')
    if 'description' not in product:
        return None
    return (product.get('description') or '').strip()


def _flat(markup):
    """The listing's HTML with the changes the venue is entitled to make removed.

    WARNING B112, and it is the store's copy of B110's lesson. The first run
    that ever got past the gate wrote the description successfully and then
    aborted, because the read-back demanded the bytes come home unchanged.
    They never will: Gumroad sanitises what it stores. Measured on the live
    page 2026-09-03, sent 3789 characters and 3791 came back, and the whole
    difference was two edits it is entitled to make -

      - a newline inserted after each of the seven <li> tags   (+7)
      - the numeric reference &#x27; decoded back to '          (-5)

    WARNING Neither the count nor the offset could have told me that. I read
    the two edits off the live page itself, with no key, out of the JSON that
    Gumroad renders into the buy page - and only then wrote this.

    WARNING This normalises for COMPARING ONLY. What is sent is `wanted`,
    untouched, exactly as description.html has it. If this were ever allowed
    near the payload it would hand the store a description with its character
    references already decoded.

    WARNING The cost, stated rather than discovered later: whitespace between
    tags stops being a difference this can see, and so does the choice between
    a character reference and the character it stands for. Both are invisible
    to a reader, and the venue overwrites both anyway - a run that insisted on
    them could never make them stick, which is the exact loop this fixes.
    """
    if markup is None:
        return None
    text = html.unescape(markup)
    # Whitespace BETWEEN tags only. Inside text it can be meaningful, and this
    # is compared against a page a buyer reads.
    text = re.sub(r'>\s+<', '><', text)
    return re.sub(r'[ \t]+', ' ', text).strip()


def main():
    token = os.environ.get('GUMROAD_TOKEN', '')
    if not token:
        fail('no GUMROAD_TOKEN in the environment')
    if not os.path.exists(SOURCE):
        fail(SOURCE + ' does not exist')
    with open(SOURCE, encoding='utf-8') as fh:
        wanted = fh.read().strip()
    if len(wanted) < MIN_CHARS:
        fail('description.html is %d characters - too short to be the real '
             'description, and a wrong one here blanks the page people buy '
             'from' % len(wanted))
    if REQUIRED_MARK not in wanted:
        fail('description.html does not contain the AI disclosure (%r), so '
             'nothing was sent' % REQUIRED_MARK)

    ident = find_id(token)
    before = live_description(token, ident)
    # WARNING B109's fifth lesson, which this script had not learned: "do I
    # need to send this" and "did it arrive" have to be the same question, or
    # the two disagree forever and the listing is rewritten on every push.
    if _flat(before) == _flat(wanted):
        note('### Store description already current\nNothing was sent.')
        record('ok (already current, nothing sent)')
        return
    call('PUT', '/products/' + ident, token, {'description': wanted})

    # Read it back. "The request returned 200" and "the page a reader opens
    # says this" are different claims, and this project has published the
    # first as if it were the second before (B77).
    after = live_description(token, ident)
    if _flat(after) == _flat(wanted):
        note('### Store description updated\n%d characters, confirmed by '
             'reading the listing back.' % len(after))
        record('ok (description written, %d characters)' % len(after))
    elif after is None:
        fail('the description was sent, but this API does not return a '
             'description field, so it could not be read back. Check the '
             'listing by hand and fix this script.')
    else:
        # WARNING B110. Say WHERE. The first version of this line reported two
        # numbers - 3789 sent, 3791 live - and two numbers cannot tell you
        # whether a store page was corrupted or whether the venue wrapped a
        # paragraph. The same push produced the same shape at the other venue,
        # which turned out to be code-fence languages being added on arrival.
        live, mine_ = _flat(after), _flat(wanted)
        at = 0
        while at < min(len(live), len(mine_)) and live[at] == mine_[at]:
            at += 1
        note('  reads back different at offset %d - sent %r, live %r'
             % (at, mine_[at:at + 80], live[at:at + 80]))
        fail('the listing was written but reads back different (%d characters '
             'sent, %d live)' % (len(wanted), len(after)))


if __name__ == '__main__':
    main()
