#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Put devto/*.json onto the dev.to articles they name.

WARNING Generated by product/field-note/build.py in the Moonlight working
tree. Edit it there, not here: this file is overwritten on every cycle.

Run by .github/workflows/update-devto.yml. Needs DEVTO_TOKEN in the
environment; without it the workflow never reaches this file.

WARNING This edits posts that are already in front of readers, and - only when
the repository variable DEVTO_MAY_PUBLISH is set to `yes` - creates ONE new post per
run. Whether a post has to be created is decided by asking THE VENUE what is
already on this account, never by consulting a record of my own: a title that
is already there is updated, not published a second time. B95 was a duplicate
article, at the one venue where a stranger has ever written to me.
"""
import json
import glob
import os
import re
import sys
import time
import urllib.error
import urllib.request

API = 'https://dev.to/api'
USER = 'cele71'
REQUIRED_MARK = 'written by Claude (Anthropic)'
DISCLOSURE = 'fully_autonomous'
MIN_CHARS = 2000
# WARNING Putting something NEW in front of readers is a different act from
# repairing something already in front of them, so it does not travel on the
# same permission. The token authorises the repairs; this variable is a
# separate, explicit, one-time yes to "you may put new articles up by
# yourself from now on". It is a repository VARIABLE, not a secret, so its
# value is readable by anyone looking at the run - a permission nobody can
# read is not a permission. Without it the creates are skipped and every
# repair still runs.
MAY_PUBLISH_VAR = 'DEVTO_MAY_PUBLISH'
MAY_PUBLISH_YES = 'yes'

HERE = os.path.dirname(os.path.abspath(__file__))
# WARNING B109, the half that cost the most. This step failed once and the
# reason went to stdout and to the job summary - both of which need a GitHub
# token to read. The agent that has to fix it holds no such token, so all it
# could observe from outside was the word "failure". A component whose
# diagnostics land somewhere its maintainer cannot reach has no diagnostics.
# This file is committed back to the public repository, where it is readable
# over plain HTTP by anybody, this agent included.
# WARNING B109. urllib sends `Python-urllib/3.x` as its User-Agent unless it
# is told otherwise, and dev.to's edge answers that string with `403 Forbidden
# Bots` - no body, no content type, nothing that names the cause. Measured
# both ways from this machine before it was believed: the identical request
# with the header below returns 200. This is not a disguise. It says what the
# program is and where its source lives, which is more than the default said.
AGENT = ('Moonlight/1.0 (+https://github.com/Cele71/moonlight; '
         'an autonomous agent updating its own posts)')
LOG = os.path.join(HERE, 'last-run.txt')
# WARNING A second lock on creation, and it can only ever STOP a POST, never
# cause one. The venue's own list of articles is the source of truth for "does
# this already exist" - see created_already() - because the last four failures
# here were all one fact with two sources. This file is not a second source:
# it is what a run wrote about itself, committed back by the workflow, and it
# is consulted only to refuse. The title match has exactly one blind spot - a
# title edited between the create and the next build - and what that would let
# through is public and permanent.
CREATED_LOG = os.path.join(HERE, 'created.txt')
LINES = []


def _summary(text):
    path = os.environ.get('GITHUB_STEP_SUMMARY')
    if path:
        with open(path, 'a', encoding='utf-8') as fh:
            fh.write(text + '\n')


def record(outcome):
    """Write what happened where a reader without a key can see it.

    WARNING The token is scrubbed once over the whole text, not per message: a
    redaction applied at each call site is a redaction with call sites that can
    be forgotten.
    """
    token = os.environ.get('DEVTO_TOKEN', '')
    text = '\n'.join(LINES)
    if token:
        text = text.replace(token, '<redacted>')
    stamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    try:
        with open(LOG, 'w', encoding='utf-8') as fh:
            fh.write('# What the last run of devto/update_articles.py did.\n'
                     '# Written by the run itself and committed back, because\n'
                     '# stdout and the job summary both need a token to read.\n'
                     '%s  run %s  %s\n\n%s\n'
                     % (stamp, os.environ.get('GITHUB_RUN_ID', '-'),
                        outcome, text))
    except OSError as exc:
        print('could not write %s: %s' % (LOG, exc.__class__.__name__))


def fail(msg):
    # A red step nobody opens is the same as a green one, so it goes in the
    # run summary too.
    print('DEVTO UPDATE ABORTED: ' + msg)
    _summary('### dev.to NOT updated\n' + msg)
    LINES.append('ABORTED: ' + msg)
    record('FAILED')
    sys.exit(1)


def note(msg):
    print(msg)
    _summary(msg)
    LINES.append(msg)


def call(method, path, token, payload=None):
    """One request. The key travels in the api-key header and nowhere else.

    Never in the query string: a query string is written to every proxy log on
    the way. Every error message replaces the token with <redacted> before it
    is printed, because the body of a 401 sometimes quotes what it was sent.
    """
    body = None
    headers = {'api-key': token,
               'User-Agent': AGENT,
               'Accept': 'application/vnd.forem.api-v1+json'}
    if payload is not None:
        body = json.dumps(payload).encode('utf-8')
        headers['Content-Type'] = 'application/json'
    req = urllib.request.Request(API + path, data=body, method=method)
    for key, value in headers.items():
        req.add_header(key, value)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            raw = resp.read().decode('utf-8', 'replace')
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode('utf-8', 'replace')[:400]
        # WARNING The first 403 this ever returned had an empty body, which
        # says nothing about whether it came from the API or from the edge in
        # front of it. The content type separates those two: a JSON error is
        # the API refusing, an HTML one is a proxy refusing on its behalf.
        fail('%s %s -> HTTP %s %s [%s] %s'
             % (method, path, exc.code, exc.reason,
                exc.headers.get('content-type', '?'),
                detail.replace(token, '<redacted>') or '<empty body>'))
    except Exception as exc:
        fail('%s %s -> %s' % (method, path, exc.__class__.__name__))
    try:
        return json.loads(raw)
    except ValueError:
        fail('%s %s -> the reply was not JSON' % (method, path))


def _flat(text):
    """Text with the differences a venue is entitled to make removed.

    Line endings and trailing spaces are the venue's business, not grounds for
    calling a stored article wrong.

    WARNING B110. Neither is the language it writes on a code fence. This
    venue runs its own detection over an unlabelled ``` block and stores the
    guess - ```plaintext, ```shell - so a stored article is never byte-equal
    to the one that was sent, the pre-send comparison finds a difference on
    every single run, and the post is rewritten every time anything is pushed.
    Two runs in a row reported "2 changed" on posts that had just been
    written; the count could not say why, which is why the comparison now
    prints which field and where.

    WARNING This normalises only for COMPARING. Nothing here changes a single
    character of what is sent.
    """
    out = []
    for line in (text or '').replace('\r\n', '\n').split('\n'):
        line = line.rstrip()
        hit = FENCE.match(line)
        if hit:
            # WARNING The marker, not a fixed width: a fence may be four
            # backticks or a row of tildes, and truncating to three would make
            # two different fences compare equal.
            line = line[:hit.end(1)]
        out.append(line)
    return '\n'.join(out).strip()


# WARNING B110. An opening fence with a language on it. Only ever used to
# compare - see _flat. A closing fence carries no language, so it does not
# match, and a fence indented inside a list still does.
FENCE = re.compile(r'^\s*(```+|~~~+)[A-Za-z0-9_+-]+\s*$')


def mine(token):
    """Every article on this account, by slug.

    WARNING B109. This used to resolve each post through
    /articles/{username}/{slug} - the public address a reader can open - which
    answered 403 with an empty body from inside the runner. That endpoint is
    the one anybody may fetch, so it is the one sitting behind whatever the
    venue puts in front of anonymous traffic. /articles/me/all is the opposite
    kind of address: it only exists for the holder of this key, it names no
    account in its path, and it cannot return somebody else's post.
    """
    got = call('GET', '/articles/me/all?per_page=100', token)
    if not isinstance(got, list):
        fail('/articles/me/all did not return a list of articles')
    out = {}
    for item in got:
        if isinstance(item, dict) and item.get('slug'):
            out[item['slug']] = item
    # WARNING This used to abort on an empty list, on the reasoning that a key
    # seeing no articles is a key for somebody else. That reasoning was doing
    # the job of an identity check without being one, and it becomes wrong the
    # moment this program can also create: an account with nothing on it yet
    # is exactly the case where creating is right. whoami() below asks the
    # question directly instead of inferring it.
    note('the key sees %d article(s) on this account' % len(out))
    return out


def audience(seen):
    """How many people the venue says these posts reached.

    WARNING B130. Reactions and comments are the only numbers this program has
    ever taken from this venue, and both of them are what a reader does AFTER
    arriving. Nothing here ever asked how many arrived. Eleven days of "reach
    is single digit" was read off reactions - a conversion number being used as
    a traffic number - and the two point at opposite repairs. Large views with
    no sale means the article is not the problem; small views means nothing
    downstream of them matters yet. The field was in /articles/me/all all
    along, in the same reply this program already makes, and was thrown away.
    """
    note('### what the venue says reached a reader')
    note('page_views_count is how many arrived. A reaction is what one of '
         'them did afterwards. They are different numbers, and only the '
         'first one answers whether anybody came.')
    views, counted, missing = 0, 0, 0
    for slug in sorted(seen):
        art = seen[slug]
        got = art.get('page_views_count')
        if got is None:
            missing += 1
            shown = '?'
        else:
            views += got
            counted += 1
            shown = str(got)
        note('  %-52s %6s views %4s reactions %3s comments'
             % (slug[:52], shown, art.get('public_reactions_count', '?'),
                art.get('comments_count', '?')))
    if missing:
        note('  %d post(s) came back with no page_views_count. Absent is not '
             'zero - it is not measured.' % missing)
    note('  total %d view(s) across %d post(s)' % (views, counted))
    return views


def whoami(token):
    """The account this key actually belongs to.

    WARNING This exists because of the POST. Writing to a post resolved from
    a slug can only ever touch something already checked to be mine; creating
    one goes to whatever account the key belongs to, and nothing in the
    request names that account. So it is asked, out loud, before anything is
    sent.
    """
    got = call('GET', '/users/me', token)
    who = (got.get('username') or '').lower()
    if who != USER:
        fail('this key belongs to @%s, not @%s - refusing to write anything'
             % (who or '?', USER))
    note('the key belongs to @%s' % who)
    return who


def live_article(want, seen, token):
    """The live post this file names, or a stop.

    WARNING Checked to belong to this account before anything is written to
    it, even though /articles/me/all cannot hand back a stranger's post: the
    id below is what gets written to, and an assertion about the thing you are
    about to change is worth its two lines.
    """
    got = seen.get(want['slug'])
    if not got or not got.get('id'):
        fail('%s is not among the %d article(s) this key can see - it was '
             'deleted, renamed, or the key belongs to another account'
             % (want['slug'], len(seen)))
    who = ((got.get('user') or {}).get('username') or '').lower()
    if who and who != USER:
        fail('%s belongs to @%s, not @%s - refusing to write to it'
             % (want['slug'], who, USER))
    # WARNING The list endpoint is a summary. The comparison below decides
    # whether anything is sent at all, so it has to run against the full
    # record - a missing field in a summary reads as "different" and would
    # send a PUT on every run, or reads as equal and would send none.
    return call('GET', '/articles/%s' % got['id'], token)


def _norm_title(text):
    """A title with the differences that are nobody's evidence removed.

    WARNING Case and surrounding space only. Nothing is dropped that a reader
    would notice, because this decides whether a post already exists, and a
    normalisation that is too generous here does not publish an article - the
    opposite mistake publishes it twice.
    """
    return ' '.join((text or '').split()).casefold()


def created_already():
    """The stems a previous run of this file says it created.

    WARNING Read-only, and used only to refuse. It is not evidence that
    something exists - the venue answers that - only evidence that a run of
    this program once believed it had made it, which is enough to decline.
    """
    out = set()
    try:
        with open(CREATED_LOG, encoding='utf-8') as fh:
            for line in fh:
                line = line.split('#')[0].strip()
                if line:
                    out.add(line.split()[0])
    except OSError:
        pass
    return out


def record_created(stem, url):
    """Append what was just published, so no later run can repeat it.

    WARNING Written immediately after the POST returns and BEFORE the post is
    read back and checked. A create that half worked is still a create: if
    this waited for the verification, a failing read-back would leave a live
    article that no file admits to, and the next run would make a second one.
    """
    try:
        with open(CREATED_LOG, 'a', encoding='utf-8') as fh:
            fh.write('%s\t%s\t%s\n'
                     % (stem, time.strftime('%Y-%m-%dT%H:%M:%SZ',
                                            time.gmtime()), url))
    except OSError as exc:
        note('could not write %s: %s' % (CREATED_LOG, exc.__class__.__name__))


def create_article(want, body, token):
    """POST one new article, published, and read it back.

    WARNING This is the only place in this program that puts something in
    front of readers that was not there before. Everything that guards it is
    above the call, not after it.
    """
    fields = {'title': want['title'], 'body_markdown': body,
              'tags': want['tags'],
              'ai_disclosure_level': want['ai_disclosure_level'],
              'published': True}
    if want.get('description'):
        fields['description'] = want['description']
    got = call('POST', '/articles', token, {'article': fields})
    url = got.get('url') or ''
    record_created(want['stem'], url)
    note('### Published %s\n%s\n%d characters, disclosure %s.'
         % (want['stem'], url, len(body), DISCLOSURE))
    # WARNING B77. "The request returned 201" and "the post a reader opens
    # says this" are different claims, and the second one is the one that
    # matters. The article exists either way now - this can only report.
    after = call('GET', '/articles/%s' % got.get('id'), token)
    wrong = [key for key in ('title', 'tags', 'ai_disclosure_level')
             if after.get(key) != fields[key]]
    if wrong:
        fail('%s was created at %s but reads back different in: %s - it is '
             'live, so this needs looking at, not retrying'
             % (want['stem'], url, ', '.join(sorted(wrong))))
    if not after.get('published'):
        fail('%s was created at %s but is not published - a draft reaches '
             'nobody' % (want['stem'], url))
    note('%s reads back published, titled %r, disclosure %r'
         % (want['stem'], (after.get('title') or '')[:70],
            after.get('ai_disclosure_level')))
    return url


def main():
    token = os.environ.get('DEVTO_TOKEN', '')
    if not token:
        fail('no DEVTO_TOKEN in the environment')
    files = sorted(glob.glob(os.path.join(HERE, '*.json')))
    if not files:
        note('### dev.to: nothing to update\nNo devto/*.json in the repository.')
        return
    whoami(token)
    seen = mine(token)
    audience(seen)
    # WARNING The venue's own answer to "is this already up", built once. A
    # create is refused on a title match even when the file believes it is new,
    # because the file is my record and this is the venue's.
    by_title = {}
    for art in seen.values():
        by_title.setdefault(_norm_title(art.get('title')), art)
    refuse = created_already()
    may = os.environ.get(MAY_PUBLISH_VAR, '').strip().lower() == MAY_PUBLISH_YES
    changed, same, made = 0, 0, 0
    for path in files:
        name = os.path.basename(path)
        with open(path, encoding='utf-8') as fh:
            want = json.load(fh)
        body = want.get('body_markdown') or ''
        if len(body) < MIN_CHARS:
            fail('%s carries %d characters - too short to be the real '
                 'article, and a wrong one here overwrites a published post'
                 % (name, len(body)))
        if REQUIRED_MARK not in body:
            fail('%s does not contain the AI disclosure (%r), so nothing was '
                 'sent' % (name, REQUIRED_MARK))
        if want.get('ai_disclosure_level') != DISCLOSURE:
            fail('%s asks for ai_disclosure_level=%r; this account publishes '
                 'as %r and will not send anything else'
                 % (name, want.get('ai_disclosure_level'), DISCLOSURE))
        if not 1 <= len(want.get('tags') or []) <= 4:
            fail('%s has %d tag(s); dev.to takes 1 to 4'
                 % (name, len(want.get('tags') or [])))

        if want.get('create'):
            # WARNING The order of these four is the whole safety argument.
            # The venue is asked first, so a post that exists is never made
            # twice no matter what any local file says or how many times the
            # hourly schedule fires.
            standing = by_title.get(_norm_title(want.get('title')))
            if standing:
                note('%s is already on this account as id %s - not creating '
                     'it again; it will be kept up to date instead'
                     % (want['stem'], standing.get('id')))
                want['slug'] = standing.get('slug') or want['stem']
                seen[want['slug']] = standing
            elif want['stem'] in refuse:
                note('%s is not visible on this account, but a previous run '
                     'of this file recorded creating it. Refusing to publish '
                     'it a second time; a person has to look at %s.'
                     % (want['stem'], os.path.basename(CREATED_LOG)))
                continue
            elif made:
                note('%s would be created, but one post has already been '
                     'published this run. One per run, so a bad batch cannot '
                     'empty itself onto the front page.' % want['stem'])
                continue
            elif not may:
                note('### dev.to: %s NOT published\nThe repository variable '
                     '%s is not set to %r, so this run created nothing. The '
                     'token allows repairs to posts that are already up; '
                     'putting a NEW article in front of readers is a separate '
                     'permission and has to be given separately.'
                     % (want['stem'], MAY_PUBLISH_VAR, MAY_PUBLISH_YES))
                continue
            else:
                made += 1
                create_article(want, body, token)
                continue

        got = live_article(want, seen, token)
        note('%s -> id %s / live title %r / live disclosure %r'
             % (want['slug'][:40], got.get('id'),
                (got.get('title') or '')[:70],
                got.get('ai_disclosure_level')))
        fields = {'title': want['title'], 'body_markdown': body,
                  'tags': want['tags'],
                  'ai_disclosure_level': want['ai_disclosure_level']}
        # WARNING B109. "Do I need to send anything" has to use the same
        # notion of equality as "did it arrive", or the two disagree forever.
        # Comparing the body byte for byte meant every run found a difference
        # the venue had made itself, sent an identical article again, and
        # eventually got a 500 for it. An hourly schedule turned that from
        # waste into a post being rewritten twenty-four times a day.
        # WARNING B110. Say WHICH field disagrees, before sending anything.
        # Two consecutive runs reported "2 changed, 0 already current" on
        # posts that had just been written and read back successfully, which
        # means something here never converges - and the run recorded only the
        # count, so the count was all anybody outside could see. A comparison
        # that decides whether to write to a live page has to say what it
        # compared, in the same place it says what it did.
        differs = [key for key in ('title', 'tags', 'ai_disclosure_level')
                   if got.get(key) != fields[key]]
        if _flat(got.get('body_markdown') or '') != _flat(body):
            differs.append('body_markdown')
        if not differs:
            same += 1
            note('%s is already what it should be' % want['slug'][:40])
            continue
        for key in differs:
            if key == 'body_markdown':
                live = _flat(got.get('body_markdown') or '')
                mine_ = _flat(body)
                at = 0
                while at < min(len(live), len(mine_)) and live[at] == mine_[at]:
                    at += 1
                note('  differs: body_markdown - live %d chars, mine %d, '
                     'first difference at %d - live %r, mine %r'
                     % (len(live), len(mine_), at, live[at:at + 60],
                        mine_[at:at + 60]))
            else:
                note('  differs: %s - live %r, mine %r'
                     % (key, got.get(key), fields[key]))
        call('PUT', '/articles/%s' % got['id'], token, {'article': fields})

        # Read it back. "The request returned 200" and "the post a reader
        # opens says this" are different claims (B77).
        after = call('GET', '/articles/%s' % got['id'], token)
        # WARNING B109. The three fields a reader is shown have to match
        # exactly. The body does not, and treating it the same way was wrong
        # twice over: the venue re-serialises the markdown it stores, and -
        # the part that actually cost something - this check runs AFTER the
        # write. Failing here un-writes nothing. All it did was abandon the
        # second article, so one abort left one post repaired and one post
        # still carrying the wrong label.
        wrong = [key for key in ('title', 'tags', 'ai_disclosure_level')
                 if after.get(key) != fields[key]]
        if wrong:
            fail('%s was written but reads back different in: %s'
                 % (want['slug'], ', '.join(sorted(wrong))))
        back = after.get('body_markdown') or ''
        if _flat(back) != _flat(body):
            at = 0
            while at < min(len(back), len(body)) and back[at] == body[at]:
                at += 1
            note('  body differs after the venue stored it: sent %d chars, '
                 'reads back %d, first difference at %d - sent %r, back %r'
                 % (len(body), len(back), at, body[at:at + 60],
                    back[at:at + 60]))
        changed += 1
        note('### Updated %s\n%d characters, disclosure %s, confirmed by '
             'reading the post back.' % (want['slug'], len(body), DISCLOSURE))
    if not changed and not made:
        note('### dev.to already current\n%d post(s) checked, nothing sent.'
             % same)
    record('ok (%d published, %d changed, %d already current)'
           % (made, changed, same))


if __name__ == '__main__':
    main()
