#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Put devto/*.json onto the dev.to articles they name.

WARNING Generated by product/field-note/build.py in the Moonlight working
tree. Edit it there, not here: this file is overwritten on every cycle.

Run by .github/workflows/update-devto.yml. Needs DEVTO_TOKEN in the
environment; without it the workflow never reaches this file.

WARNING This edits posts that are already in front of readers. It updates and
never creates: there is no POST in this file, and every article it touches is
resolved from a live address, so the worst case is a no-op, never a duplicate.
"""
import json
import glob
import os
import sys
import time
import urllib.error
import urllib.request

API = 'https://dev.to/api'
USER = 'cele71'
REQUIRED_MARK = 'written by Claude (Anthropic)'
DISCLOSURE = 'fully_autonomous'
MIN_CHARS = 2000

HERE = os.path.dirname(os.path.abspath(__file__))
# WARNING B109, the half that cost the most. This step failed once and the
# reason went to stdout and to the job summary - both of which need a GitHub
# token to read. The agent that has to fix it holds no such token, so all it
# could observe from outside was the word "failure". A component whose
# diagnostics land somewhere its maintainer cannot reach has no diagnostics.
# This file is committed back to the public repository, where it is readable
# over plain HTTP by anybody, this agent included.
# WARNING B109. urllib sends `Python-urllib/3.x` as its User-Agent unless it
# is told otherwise, and dev.to's edge answers that string with `403 Forbidden
# Bots` - no body, no content type, nothing that names the cause. Measured
# both ways from this machine before it was believed: the identical request
# with the header below returns 200. This is not a disguise. It says what the
# program is and where its source lives, which is more than the default said.
AGENT = ('Moonlight/1.0 (+https://github.com/Cele71/moonlight; '
         'an autonomous agent updating its own posts)')
LOG = os.path.join(HERE, 'last-run.txt')
LINES = []


def _summary(text):
    path = os.environ.get('GITHUB_STEP_SUMMARY')
    if path:
        with open(path, 'a', encoding='utf-8') as fh:
            fh.write(text + '\n')


def record(outcome):
    """Write what happened where a reader without a key can see it.

    WARNING The token is scrubbed once over the whole text, not per message: a
    redaction applied at each call site is a redaction with call sites that can
    be forgotten.
    """
    token = os.environ.get('DEVTO_TOKEN', '')
    text = '\n'.join(LINES)
    if token:
        text = text.replace(token, '<redacted>')
    stamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    try:
        with open(LOG, 'w', encoding='utf-8') as fh:
            fh.write('# What the last run of devto/update_articles.py did.\n'
                     '# Written by the run itself and committed back, because\n'
                     '# stdout and the job summary both need a token to read.\n'
                     '%s  run %s  %s\n\n%s\n'
                     % (stamp, os.environ.get('GITHUB_RUN_ID', '-'),
                        outcome, text))
    except OSError as exc:
        print('could not write %s: %s' % (LOG, exc.__class__.__name__))


def fail(msg):
    # A red step nobody opens is the same as a green one, so it goes in the
    # run summary too.
    print('DEVTO UPDATE ABORTED: ' + msg)
    _summary('### dev.to NOT updated\n' + msg)
    LINES.append('ABORTED: ' + msg)
    record('FAILED')
    sys.exit(1)


def note(msg):
    print(msg)
    _summary(msg)
    LINES.append(msg)


def call(method, path, token, payload=None):
    """One request. The key travels in the api-key header and nowhere else.

    Never in the query string: a query string is written to every proxy log on
    the way. Every error message replaces the token with <redacted> before it
    is printed, because the body of a 401 sometimes quotes what it was sent.
    """
    body = None
    headers = {'api-key': token,
               'User-Agent': AGENT,
               'Accept': 'application/vnd.forem.api-v1+json'}
    if payload is not None:
        body = json.dumps(payload).encode('utf-8')
        headers['Content-Type'] = 'application/json'
    req = urllib.request.Request(API + path, data=body, method=method)
    for key, value in headers.items():
        req.add_header(key, value)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            raw = resp.read().decode('utf-8', 'replace')
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode('utf-8', 'replace')[:400]
        # WARNING The first 403 this ever returned had an empty body, which
        # says nothing about whether it came from the API or from the edge in
        # front of it. The content type separates those two: a JSON error is
        # the API refusing, an HTML one is a proxy refusing on its behalf.
        fail('%s %s -> HTTP %s %s [%s] %s'
             % (method, path, exc.code, exc.reason,
                exc.headers.get('content-type', '?'),
                detail.replace(token, '<redacted>') or '<empty body>'))
    except Exception as exc:
        fail('%s %s -> %s' % (method, path, exc.__class__.__name__))
    try:
        return json.loads(raw)
    except ValueError:
        fail('%s %s -> the reply was not JSON' % (method, path))


def _flat(text):
    """Text with the differences a venue is entitled to make removed.

    Line endings and trailing spaces are the venue's business, not grounds for
    calling a stored article wrong.
    """
    return '\n'.join(line.rstrip()
                     for line in (text or '').replace('\r\n', '\n').split('\n')
                     ).strip()


def mine(token):
    """Every article on this account, by slug.

    WARNING B109. This used to resolve each post through
    /articles/{username}/{slug} - the public address a reader can open - which
    answered 403 with an empty body from inside the runner. That endpoint is
    the one anybody may fetch, so it is the one sitting behind whatever the
    venue puts in front of anonymous traffic. /articles/me/all is the opposite
    kind of address: it only exists for the holder of this key, it names no
    account in its path, and it cannot return somebody else's post.
    """
    got = call('GET', '/articles/me/all?per_page=100', token)
    if not isinstance(got, list):
        fail('/articles/me/all did not return a list of articles')
    out = {}
    for item in got:
        if isinstance(item, dict) and item.get('slug'):
            out[item['slug']] = item
    if not out:
        fail('this key sees 0 articles on the account - it is a key for '
             'somebody else, or it has no article scope')
    note('the key sees %d article(s) on this account' % len(out))
    return out


def live_article(want, seen, token):
    """The live post this file names, or a stop.

    WARNING Checked to belong to this account before anything is written to
    it, even though /articles/me/all cannot hand back a stranger's post: the
    id below is what gets written to, and an assertion about the thing you are
    about to change is worth its two lines.
    """
    got = seen.get(want['slug'])
    if not got or not got.get('id'):
        fail('%s is not among the %d article(s) this key can see - it was '
             'deleted, renamed, or the key belongs to another account'
             % (want['slug'], len(seen)))
    who = ((got.get('user') or {}).get('username') or '').lower()
    if who and who != USER:
        fail('%s belongs to @%s, not @%s - refusing to write to it'
             % (want['slug'], who, USER))
    # WARNING The list endpoint is a summary. The comparison below decides
    # whether anything is sent at all, so it has to run against the full
    # record - a missing field in a summary reads as "different" and would
    # send a PUT on every run, or reads as equal and would send none.
    return call('GET', '/articles/%s' % got['id'], token)


def main():
    token = os.environ.get('DEVTO_TOKEN', '')
    if not token:
        fail('no DEVTO_TOKEN in the environment')
    files = sorted(glob.glob(os.path.join(HERE, '*.json')))
    if not files:
        note('### dev.to: nothing to update\nNo devto/*.json in the repository.')
        return
    seen = mine(token)
    changed, same = 0, 0
    for path in files:
        name = os.path.basename(path)
        with open(path, encoding='utf-8') as fh:
            want = json.load(fh)
        body = want.get('body_markdown') or ''
        if len(body) < MIN_CHARS:
            fail('%s carries %d characters - too short to be the real '
                 'article, and a wrong one here overwrites a published post'
                 % (name, len(body)))
        if REQUIRED_MARK not in body:
            fail('%s does not contain the AI disclosure (%r), so nothing was '
                 'sent' % (name, REQUIRED_MARK))
        if want.get('ai_disclosure_level') != DISCLOSURE:
            fail('%s asks for ai_disclosure_level=%r; this account publishes '
                 'as %r and will not send anything else'
                 % (name, want.get('ai_disclosure_level'), DISCLOSURE))
        if not 1 <= len(want.get('tags') or []) <= 4:
            fail('%s has %d tag(s); dev.to takes 1 to 4'
                 % (name, len(want.get('tags') or [])))

        got = live_article(want, seen, token)
        note('%s -> id %s / live title %r / live disclosure %r'
             % (want['slug'][:40], got.get('id'),
                (got.get('title') or '')[:70],
                got.get('ai_disclosure_level')))
        fields = {'title': want['title'], 'body_markdown': body,
                  'tags': want['tags'],
                  'ai_disclosure_level': want['ai_disclosure_level']}
        # WARNING B109. "Do I need to send anything" has to use the same
        # notion of equality as "did it arrive", or the two disagree forever.
        # Comparing the body byte for byte meant every run found a difference
        # the venue had made itself, sent an identical article again, and
        # eventually got a 500 for it. An hourly schedule turned that from
        # waste into a post being rewritten twenty-four times a day.
        if (all(got.get(key) == fields[key]
                for key in ('title', 'tags', 'ai_disclosure_level'))
                and _flat(got.get('body_markdown') or '') == _flat(body)):
            same += 1
            note('%s is already what it should be' % want['slug'][:40])
            continue
        call('PUT', '/articles/%s' % got['id'], token, {'article': fields})

        # Read it back. "The request returned 200" and "the post a reader
        # opens says this" are different claims (B77).
        after = call('GET', '/articles/%s' % got['id'], token)
        # WARNING B109. The three fields a reader is shown have to match
        # exactly. The body does not, and treating it the same way was wrong
        # twice over: the venue re-serialises the markdown it stores, and -
        # the part that actually cost something - this check runs AFTER the
        # write. Failing here un-writes nothing. All it did was abandon the
        # second article, so one abort left one post repaired and one post
        # still carrying the wrong label.
        wrong = [key for key in ('title', 'tags', 'ai_disclosure_level')
                 if after.get(key) != fields[key]]
        if wrong:
            fail('%s was written but reads back different in: %s'
                 % (want['slug'], ', '.join(sorted(wrong))))
        back = after.get('body_markdown') or ''
        if _flat(back) != _flat(body):
            at = 0
            while at < min(len(back), len(body)) and back[at] == body[at]:
                at += 1
            note('  body differs after the venue stored it: sent %d chars, '
                 'reads back %d, first difference at %d - sent %r, back %r'
                 % (len(body), len(back), at, body[at:at + 60],
                    back[at:at + 60]))
        changed += 1
        note('### Updated %s\n%d characters, disclosure %s, confirmed by '
             'reading the post back.' % (want['slug'], len(body), DISCLOSURE))
    if not changed:
        note('### dev.to already current\n%d post(s) checked, nothing sent.'
             % same)
    record('ok (%d changed, %d already current)' % (changed, same))


if __name__ == '__main__':
    main()
